### ISSUE TITLE
Log out is not working when api returns 401 Unauthorized 

### ISSUE THREAD

**Issue by lucia-santos** [rootstrap/react-redux-base#168]
### Problem

Nothing is done when api returns `Error 401 unauthorized`. 

It is expected in `applyDefaultInterceptors` in `defaultResponseInterceptors` to logout when this error occurs but it is not working:

```
const defaultResponseInterceptors = store => [
  async response => {
    if (response.ok) {
        ...
      }
    }
    if (response.status === UNAUTHORIZED) {
      store.dispatch(logout());
    }
    return response;
  }
];

export default (store, apiService) => {
  defaultResponseInterceptors(store).forEach(interceptor =>
    apiService.responseInterceptors.use(interceptor)
  );
};
```
The problem in the  previous code is that in `apiService.responseInterceptors.use(interceptor)` the use method expects two functions as parameters (first one in case of fulfill and second one in case of failure) but is only being passed the fulfill parameter. 

### Possible Solution

A possible solution we encountered was to divide de `defaultResponseInterceptors` in two separate functions: one for fulfill and another one in case of failure (with the unauthorized logic in it) to pass both of them to the `use` method. 

```
apiService.responseInterceptors.use(
    defaultFulfillResponseInterceptor(store),
    defaultFailureResponseInterceptor(store)
  );
```

**Comment by bernabe9** [comment]
This bug was introduced after the api service refactor (https://github.com/rootstrap/react-redux-base/pull/140)

^ @mcousillas6

**Comment by bernabe9** [comment]
As an addition, I think we should document how the interceptors work

**Comment by mcousillas6** [comment]
The proposed solution looks good to me. Do any of you guys have time to open up a PR?

> As an addition, I think we should document how the interceptors work

Definitely, they are inspired on axios' interceptors, but we should add inline docs + a section on the readme. The whole apiService needs way more docs than it has now.
