### ISSUE TITLE
Go to login when api returns 401 unauthorized

### ISSUE THREAD

**Issue by aguscha333** [rootstrap/react-redux-base#97]
### Problem
Users can continue to navigate the site if they logged out on another tab. This is the use case that i found where this happens.

The problem in the code is that in that case session can't be loaded since it does not exist anymore so it ends up in the catch and does nothing:
```
    sessionService.loadSession()
      .then(() => {
        if (response.status === 401) {
          sessionService.deleteSession();
          window.location = routes.login;
        }
      }).catch(() => {});
```

### Solution
This is the solution I came up with in my project, if we agree that this is a good solution I can create a PR to add it to the base.
```
    sessionService.loadSession()
      .then(() => {
        if (response.status === 401) {
          sessionService.deleteSession();
          window.location = routes.login;
        }
      }).catch(() => {
        window.location = routes.login;
      });
```

**Comment by bernabe9** [comment]
I only see one downside to your workaround. What happens if the user isn't navigating to an authorized page? We will redirect it to the login page anyways :(

I'd prefer something like this:

```javascript
sessionService.loadSession()
  .then(() => {
    if (response.status === 401) {
      sessionService.deleteSession();
      window.location = routes.login;
    }
  }).catch(() => {
    if (response.status === 401) {
      window.location = routes.login;
    }
  });
```

If the user isn't receiving a 401 means that the user is allowed to navigate to the page.

**Comment by fsarachu** [comment]
I agree there is a problem, but that solution would cause a login page reload on a failed login too, not good.
I think the main problem is that the redirect is being handled imperatively here.
How about handling it declaratively with react-router, inside the ProtectedRoute component?

**Comment by bernabe9** [comment]
Issue fixed here: https://github.com/rootstrap/react-redux-base/pull/99
